language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

# command to install dependencies
install:
  - python setup.py build sdist
  - pip install -r requirements.pip
# command to run tests
script: nosetests --verbosity 2
